version: '2.4'

services:
  tg-tracker:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: tg-tracker:latest
    container_name: tg-tracker
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '2'
    environment:
        TZ : "Europe/London"
    volumes:
      - ./.storage:/data:rw
      - ./config/config.toml:/config/config.toml:ro
